### ISSUE TITLE
Steam fails to launch GOG games

### ISSUE THREAD

**Issue by redromnon** [redromnon/HeroicBashLauncher#10]
I found that bash scripts or launch files of GOG games fail to launch from Steam but not from the terminal or Lutris as of now. This may also affect other users.

The issue is connected to the current version of heroic-gogdl binary being used in Heroic 2.2.1. The solution is fairly easy to implement - you need to use the **testing** branch of the binary.

I've provided the [link to the binary of the current latest commit that works with Steam](https://github.com/Heroic-Games-Launcher/heroic-gogdl/suites/5477976540/artifacts/174697991). Once you download it, just extract and replace it with the one Heroic uses in `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/` or you can just wait for Heroic to make use of a newer version on gogdl binary.

**Comment by 44-k** [comment]
I have tried the fix you suggested on the AppImage version of Heroic 2.2.1. Unpacked the AppImage, replaced gogdl with v0.2, and rebuilt the AppImage.

I can now run GOG games from Steam but only if Heroic is running in the background. Otherwise I get an error. Have I missed something?

https://user-images.githubusercontent.com/101119432/157069269-bd7fdbf1-6990-45e0-8301-0b3f3f1d9fa5.mp4

**Comment by redromnon** [comment]
There's nothing you have missed. The thing is, the current version of Heroic i.e. 2.2.1, doesn't support alternate binary for gogdl but only for legendary. That's why Heroic always needs to be kept running while launching GOG games and not for Epic games.

Both Heroic and Bash Launcher's upcoming versions will be taking care of this.

**Comment by redromnon** [comment]
GOG games should now launch with the new Heroic v2.2.2 and Bash Launcher v2.1.0

**Comment by 44-k** [comment]
I can confirm I'm now able to launch GOG games from Steam without Heroic running in the background 🎉

Just a note, a had to make binaries/gogdl executable because I was getting this error:
`./TheWitcherWildHuntGameoftheYearEdition_Heroic.sh: line 12: /home/deck/Games/HeroicBashLauncher/binaries/gogdl: Permission denied`

Thanks a lot!
