### ISSUE TITLE
[Bug] Anti-Cheat Runtime is a directory

### ISSUE THREAD

**Issue by HeffeHam** [redromnon/HeroicBashLauncher#101]
[FallGuys_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/9459232/FallGuys_Heroic.log)
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
fall guys wont launch

**To Reproduce**
https://guidefall.com/fall-guys-steam-deck-how-to-download/

**Expected behavior**
fall guys should launch from steam

**Screenshots**

**Details**

 - Platform: [Steam Deck]
 - OS: [steamos]
 - Heroic Version: 2.4.1
 - Bash Launcher Version: 2.9.1
**Additional context**

**Comment by redromnon** [comment]
Thanks for creating this issue! I forgot to add `PROTON_(EAC/BATTLEYE)_RUNTIME` to the anti-cheat parameters.

Do let me know if this build works - https://github.com/redromnon/HeroicBashLauncher/actions/runs/2963634234

Moreover, you can skip step 8 from that guide since it looks like you've already enabled EAC runtime for Fall Guys in Heroic.

**Comment by HeffeHam** [comment]
thank you for quick fix!!!!!

**Comment by redromnon** [comment]
Please confirm if this works for you.

**Comment by HeffeHam** [comment]
Confirmed!
