### ISSUE TITLE
Rename .sh to .py

### ISSUE THREAD

**Issue by Zebouski** [redromnon/HeroicBashLauncher#4]
When I see .sh files, I usually just type `$ bash filename.sh` instead of marking it as executable and running it itself in the terminal. The fact that ./HeroicBashLauncher.sh is actually a python3 script caught me off guard. My desktop completely froze for a solid 30 seconds before I could get bash to stop trying to execute the script. I'd appreciate a file rename

**Comment by redromnon** [comment]
I understand that it's natural for some users to use `bash` for executing bash scripts.

But, it is understood that users go through the installation/usage section at least once. The steps are clearly mentioned there. Moreover, any Linux newbie will just double-click the file or just use `./` if at all he/she uses the terminal in most cases (since it's mentioned in the readme file).

Thanks for the heads up anyway. I may implement the change in the next update.

**Comment by redromnon** [comment]
This issue has been solved in Version 1.5.
