### ISSUE TITLE
[Bug] Kingdom Hearts 2.8 not launching from steam

### ISSUE THREAD

**Issue by Martos** [redromnon/HeroicBashLauncher#59]
### Before posting this issue, make sure you've read the [Issues section in the Readme](https://github.com/redromnon/HeroicBashLauncher#issues-and-suggestions) and the [Flatpak/Steam-Deck guide](https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide).

**Describe the bug**
When i run the generated .sh file, the game run fine. When i try to run from steam, the game not working at all

**To Reproduce**
1. Install Kingdom Hearts 2.8 from Heroic Flatpak
2. Run HeroicBashLauncher
3. Run from Steam

**Expected behavior**
The game should run.

**Screenshots**

**Details**

 - Platform: Steam Deck
 - OS: Steam OS
 - Heroic Version: 2.5.0 Flatpak
 - Bash Launcher Version: 2.5.0 Flatpak

**Additional context**
I have the same problem with Kingdom Hearts 3

**Comment by LAA612** [comment]
Have the same issue with all KH games. It seems a problem with the sh scripts as I found they wouldn't work manually loading them either, resulting an launcher being in offline mode error, mostly giving the only option to close the title, sometimes with the option to retry that does work.
I noticed:
1. It claims the sh scripts should be added to GameFiles folder, but they aren't.
2. The issue seems to be because of the launcher being in offline mode at least in my case. I was able to circumvent it on KH 1.5/2.5 by downloading network fixes for them, but it doesn't fix it for KH3, which gets to a "checking save data" loop forever.

**Comment by redromnon** [comment]
@Martos Can you try looking at the game's log under `/GameFiles/logs`? You should spot some errors. 
By the way, there's a [video guide](https://www.youtube.com/watch?v=CyWgdeHaccs&list=PLeDC5_PzNVZwfWrHulv0oTtFIUG5jQ7DC) I came across and I think it might also work for the other KH games.

**Comment by Martos** [comment]
I attached log from gamefiles 

[KINGDOMHEARTSHD28FinalChapterPrologue_Heroic.log](https://github.com/redromnon/HeroicBashLauncher/files/8669513/KINGDOMHEARTSHD28FinalChapterPrologue_Heroic.log)


Picture when i try to run from steam
![IMG_1382](https://user-images.githubusercontent.com/4572919/167840630-e4d635d0-050f-479a-8ba9-ae47d5f2ae51.jpg)

Picture when i try to run from Heroic
![IMG_1383](https://user-images.githubusercontent.com/4572919/167841015-f321d3f3-6dd2-471a-9984-199857c824b7.jpg)

**Comment by redromnon** [comment]
Looks like a Proton error. Try using Proton-GE or Wine-GE by downloading from Heroic's Wine Manager.

**Comment by redromnon** [comment]
Closing issue.
