### ISSUE TITLE
[Bug] Failed to launch Fall Guys  Please check the game log under GameFiles/logs/ in the HeroicBashLauncher folder for the error and consider reporting it as an issue on GitHub.

### ISSUE THREAD

**Issue by dodolereporter** [redromnon/HeroicBashLauncher#88]
Hi, i'm on POP OS,
I have this when i try to start Fall Guys : Failed to launch Fall Guys

Please check the game log under GameFiles/logs/ in the HeroicBashLauncher folder for the error and consider reporting it as an issue on GitHub.

 and log file is :

ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
3.42.1
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using Bash Launcher v2.7.5
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

Checking if Zenity is installed...
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
./launchflatpakgame.sh: line 12: /home/dorian/Games/Heroic/HeroicBashLauncher-2.7.5/binaries/legendary: No such file or directory
pid 4 != 2, skipping destruction (fork without exec?)
---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---
./launchflatpakgame.sh: line 12: /home/dorian/Games/Heroic/HeroicBashLauncher-2.7.5/binaries/legendary: No such file or directory
pid 6 != 2, skipping destruction (fork without exec?)
pid 5 != 2, skipping destruction (fork without exec?)
pid 3 != 2, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Gtk-Message: 23:45:39.148: Failed to load module "appmenu-gtk-module"
Gtk-Message: 23:45:39.205: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:45:39.205: Failed to load module "canberra-gtk-module"

(zenity:8): Gdk-CRITICAL **: 23:47:13.790: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
pid 7 != 2, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dorian/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wineserver stopped
Fall Guys stopped

This is a bug or it's me ?

Thx

**Comment by redromnon** [comment]
It's trying to look for a binaries folder intended for Heroic AppImage users which it isn't supposed to since you're using Heroic Flatpak. 

Do you have this path - `/var/lib/flatpak/app/com.heroicgameslauncher.hgl` on your system? 
Just copy that path in the terminal and you should get something like - `bash: /var/lib/flatpak/app/com.heroicgameslauncher.hgl: Is a directory`

**Comment by sam-ozak** [comment]
> 

I got the same problem and yes  i copied the dir and : /var/lib/flatpak/app/com.heroicgameslauncher.hgl
bash: /var/lib/flatpak/app/com.heroicgameslauncher.hgl: No such file or directory

**Comment by redromnon** [comment]
@sam-ozak Did you have the exact same error in the log file mentioned above?

**Comment by dodolereporter** [comment]
So I'm here ^^
So the command line return : bash: /var/lib/flatpak/app/com.heroicgameslauncher.hgl: Aucun fichier ou dossier de ce type
In English : No directory or file found

**Comment by redromnon** [comment]
@sam-ozak You've shared Heroic's log file. There is a separate one for HBL (`HeroicBashLauncher/GameFiles/logs`)

**Comment by redromnon** [comment]
@dodolereporter Have you downloaded Heroic as a Flatpak (like from the software store) or as a .deb file?

**Comment by dodolereporter** [comment]
> @dodolereporter Have you downloaded Heroic as a Flatpak (like from the software store) or as a .deb file? Or did have Heroic Flatpak installed earlier?

I install heroic launcher from flatpak

**Comment by redromnon** [comment]
The only reason I can think of HBL trying to find the `binaries` folder is it's not able to find `/app/bin/heroic` while launching the game. `/app/bin/heroic` path is present in the Flatpak environment when you run your game from Heroic.

As a **workaround**, you can create the `binaries` folder next to `GameFiles` folder. Then download and extract legendary in `binaries`.  Don't forget to make it executable.

**Comment by dodolereporter** [comment]
Now the anti cheat start but it freeze and the game won't start

**Comment by redromnon** [comment]
This is a game issue and not a HBL issue. I can't discuss game issues here. Please use Discord.

**Comment by Pverte** [comment]
Hello ! I've got the same issue, with Fall Guys also, but some line of the logs are different, I'm using also Pop!Os, and Heroic isn't installed with flatpack
`ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
3.42.1
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using Bash Launcher v2.8.0
NOTE - This is an independent project and not affiliated with Heroic Games Launcher.

ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/pverte/.var/app/com.valvesoftware.Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point'
[8665] Failed to execute script 'cli' due to unhandled exception!
---CANNOT CONNECT TO NETWORK. RUNNING IN OFFLINE MODE---
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/pverte/.var/app/com.valvesoftware.Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point'
[8677] Failed to execute script 'cli' due to unhandled exception!
pid 8675 != 8649, skipping destruction (fork without exec?)
pid 8663 != 8649, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 8681 != 8649, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/pverte/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wineserver stopped
Fall Guys stopped`

**Comment by redromnon** [comment]
Have you installed the Flatpak version of Steam?

**Comment by Pverte** [comment]
Just got solved ! I just needed to make a `ln -s /home/pverte/.steam/debian-installation/steamapps/ steamapps` into `/home/pverte/.var/app/com.valvesoftware.Steam/`

**Comment by redromnon** [comment]
Closing this issue as solved.
